# ===================================================================
# Cấu hình JMX Exporter - Phiên bản đầy đủ cho Spark Worker
# ===================================================================
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  # =================================================
  # METRICS CỦA SPARK WORKER
  # =================================================
  - pattern: "org.apache.spark.deploy.worker.Worker<name=Worker><>(coresFree|coresUsed|executors|memFree_MB|memUsed_MB)"
    name: "spark_worker_{$1}"
    type: GAUGE

  # =================================================
  # METRICS HỆ ĐIỀU HÀNH (OS) - MỚI
  # Cung cấp thông tin về tài nguyên hệ thống mà JVM đang thấy.
  # =================================================
  - pattern: 'java.lang<type=OperatingSystem><>(ProcessCpuLoad|SystemCpuLoad|ProcessCpuTime|AvailableProcessors)'
    name: 'os_{$1}'
    type: GAUGE
  - pattern: 'java.lang<type=OperatingSystem><>(TotalPhysicalMemorySize|FreePhysicalMemorySize|CommittedVirtualMemorySize)'
    name: 'os_memory_bytes_{$1}'
    type: GAUGE

  # =================================================
  # METRICS CỦA MÁY ẢO JAVA (JVM)
  # =================================================
  - pattern: 'java.lang<type=Memory><(HeapMemoryUsage|NonHeapMemoryUsage)><>((?:committed|init|max|used))'
    name: 'jvm_memory_bytes_{$3}'
    labels:
      area: '$1'
    type: GAUGE

  - pattern: 'java.lang<type=GarbageCollector, name=([^>]+)><(CollectionTime|CollectionCount)>'
    name: 'jvm_gc_collection_{$2}'
    labels:
      gc: '$1'
    type: COUNTER
    
  - pattern: 'java.lang<type=Threading><(ThreadCount|DaemonThreadCount|PeakThreadCount)>'
    name: 'jvm_threading_{$1}'
    type: GAUGE