version: '2'

services:

    kafka-0:
        images: confluentinc/cp-kafka:7.6.5
        container_name: kafka-0
        hostname: kafka-0
        volumes:
            - "kafka-data-0:"
        ports:
            - '9094:9094'
        environment: KAFKA_NODE_ID=1 KAFKA_PROCESS_ROLES=broker,controller KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093 CLUSTER_ID=2qVoY3q1Q5O5hH1XVvqLmg KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094 KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-0:29092,DOCKER_NETWORK://kafka-0:9092,EXTERNAL://localhost:9094 KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3 KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3 KAFKA_AUTO_CREATE_TOPICS_ENALBED=true KAFKA_NUM_PARTITIONS=3 KAFKA_SASL_ENBLED_MECHANISMS=PLAIN KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN KAFKA_OPTS= -"Djava.security.auth.login.config=/etc/kafka/secrets/kafka_client_jaas.conf"

    kafka-1:
        images: confluentinc/cp-kafka:7.6.5
        container_name: kafka-1
        hostname: kafka-1
        ports:
            - '9094:9094'
        environment: KAFKA_NODE_ID=1 KAFKA_PROCESS_ROLES=broker,controller KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093 CLUSTER_ID=2qVoY3q1Q5O5hH1XVvqLmg KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094 KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-0:29092,DOCKER_NETWORK://kafka-0:9092,EXTERNAL://localhost:9094 KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3 KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3 KAFKA_AUTO_CREATE_TOPICS_ENALBED=true KAFKA_NUM_PARTITIONS=3 KAFKA_SASL_ENBLED_MECHANISMS=PLAIN KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN KAFKA_OPTS= -"Djava.security.auth.login.config=/etc/kafka/secrets/kafka_client_jaas.conf"

    kafka-2:
        images: confluentinc/cp-kafka:7.6.5
        container_name: kafka-2
        hostname: kafka-2
        ports:
            - '9094:9094'
        environment: KAFKA_NODE_ID=1 KAFKA_PROCESS_ROLES=broker,controller KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093 CLUSTER_ID=2qVoY3q1Q5O5hH1XVvqLmg KAFKA_LISTENERS=CONTROLLER://:9093,INTERNAL://:29092,,DOCKER_NETWORK://:9092,EXTERNAL://0.0.0.0:9094 KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-0:29092,DOCKER_NETWORK://kafka-0:9092,EXTERNAL://localhost:9094 KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,DOCKER_NETWORK:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3 KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3 KAFKA_AUTO_CREATE_TOPICS_ENALBED=true KAFKA_NUM_PARTITIONS=3 KAFKA_SASL_ENBLED_MECHANISMS=PLAIN KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN KAFKA_OPTS= -"Djava.security.auth.login.config=/etc/kafka/secrets/kafka_client_jaas.conf"

    akhq:
        image: 'tchiotludo/akhq:0.25.1'
        container_name: akhq
        ports:
            - '8080:8080'
        environment:
            AKHQ_CONFIGURATION: |
                akhq:
                    connections:
                        kafka-server:
                            properties:
                                bootstrap.servers: "kafka-0:9092,kafka-1:9092,kafka-2:9092"
                                security.protocol: SASL_PLAINTEXT
                                sasl.mechanism: PLAIN
                                sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="admin";
                    security:
                        default-group: no-roles
                        basic-auth:
                            - username: admin
                                password: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
                                passwordHash: SHA256
                                groups:
                                    - admin
                        micronaut:
                            security:
                                enabled: true
                                token:
                                    jwt:
                                        signatures:
                                            secret:
                                                generator:
                                                    secret: "6661a0975cd371c713f66a94bcd51ec874e0b040aec61f025964ad5fe7ee3120"
