{
 "title": "Spark Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{job=\"spark-master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_cpu_processors{instance=\"spark-master:5556\", job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Driver CPU/ Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Driver CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"spark-master\"}[1m]) * 100 \r\n/ jvm_cpu_processors{job=\"spark-master\"}",
     "legendFormat": "Spark Master Driver CPU"
    }
   ]
  },
  {
   "title": "Driver Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{job=\"spark-master\"})\r\n",
     "legendFormat": "Driver Memory Usage"
    }
   ]
  },
  {
   "title": "Driver GC: Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"spark-master\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Driver Memory Heap/Non-Heap Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "Memory Heap",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", instance=\"spark-master:5556\", job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Non-Heap",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area=\"nonheap\", instance=\"spark-master:5556\", job=\"spark-master\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}