FROM apache/airflow:slim-2.10.5-python3.11


USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*
USER airflow


RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-kafka \
    apache-airflow-providers-postgres \
    apache-airflow-providers-common-sql \
    confluent-kafka \
    pandas \
    pyspark

WORKDIR /opt/airflow