FROM apache/airflow:slim-2.10.5-python3.11


USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    procps \
    openjdk-17-jdk \
    build-essential \
    libpq-dev \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*
USER airflow

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH
ENV PYTHONPATH=/opt/airflow/.local/lib/python3.11/site-packages

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /opt/airflow